site_name: PRESTO
site_description: Unified immunoinformatics for MHC presentation and TCR recognition
theme:
  name: readthedocs
nav:
  - Home: index.md
  - CLI: cli.md
  - Architecture: architecture.md
  - Curriculum: curriculum.md
