"""Non-MHC shotgun proteomics corpus (MS detectability + excision).

This is the branch that makes ``ms_detectability`` identifiable. Trained only
on immunopeptidomics, the model cannot separate

- ``excision`` — was this peptide produced at all? — from
- ``detect``     — would this peptide fly in the mass spectrometer?

because both are functions of peptide sequence and never vary independently.
Shotgun proteomics breaks the confound: within one protease arm the excision
term is ~1 by construction for any fully-cleaved candidate, so observed versus
not-observed is attributable to detectability alone. Across arms, the same
protein pool is cut by four different enzymes on one instrument, so the
difference is attributable to excision alone.

Two supervision signals come out of this module:

``ms_detectability_label``
    Graded, from the fractionation-depth ladder. Bekker-Jensen ran HeLa at
    12/14/39/46/50/70 fractions; a peptide seen in a shallow run is highly
    detectable, one that only appears in the deepest run is marginal. Combined
    with ``n_replicates_detected`` (1/2/3) this is an ordinal target, which is
    better supervision than presence/absence and does not depend on
    peptide-level intensities landing (hitlist#95).

``excision_label``
    Whether machinery ``M`` would produce this peptide. Positives are the
    peptides an arm actually observed. Negatives are generated by relabeling a
    peptide with an enzyme whose cleavage rule its termini violate — a
    chymotryptic peptide ending in F is not something GluC would produce. The
    rules are exact, so these negatives are correct by construction rather than
    sampled.

Two limitations, deliberate and recorded.

Bulk rows carry no flanking sequence, because ``load_bulk_peptides`` returns
peptide coordinates (``uniprot_acc``, ``start_position``, ``end_position``) but
not the source protein sequence. So ``s_N`` sees ``<MISSING>`` on this branch
and the excision signal is carried by ``s_C`` alone. That is the correct
half: the C-terminal junction is where the protease rule lives. Wiring the
proteome in would light up ``s_N`` as well.

Second: true detectability negatives require
enumerating the in-silico digest of each source protein and subtracting the
observed set, which needs protein sequences this module does not fetch. Pass
``protein_sequences`` to enable them; otherwise the detectability target is the
depth-graded signal over observed peptides only. See hitlist#361 and
tasks/protease_detectability_spec.md S3.2.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from .vocab import (
    EXCISION_MACHINERY_TO_IDX,
    EXCISION_P1_PRIME_BLOCKED,
    EXCISION_P1_RULES,
)

# hitlist's canonical enzyme strings -> Presto machinery names.
ENZYME_TO_MACHINERY = {
    "Trypsin/P (cleaves K/R except before P)": "trypsin",
    "Trypsin/P": "trypsin",
    "Trypsin": "trypsin",
    "Chymotrypsin": "chymotrypsin",
    "LysC": "lysc",
    "GluC": "gluc",
}

# Depth ladder -> detectability target. A peptide first seen in a shallow run
# is easy to detect; one that only shows up at 70 fractions is marginal.
_DEPTH_SCORE = {12: 1.0, 14: 1.0, 39: 0.8, 46: 0.7, 50: 0.6, 70: 0.4}
_DEFAULT_DEPTH_SCORE = 0.6


@dataclass
class BulkMSRecord:
    """One shotgun-MS observation or in-silico candidate."""

    peptide: str
    machinery: str = "trypsin"
    flank_n: str = ""
    flank_c: str = ""
    detectability_label: Optional[float] = None
    excision_label: Optional[float] = None
    protein_id: str = ""
    cell_line: str = ""
    n_fractions: int = 0
    n_replicates_detected: int = 0
    observed: bool = True
    source: str = "bulk_proteomics"
    acquisition: Dict[str, Any] = field(default_factory=dict)


def machinery_for_enzyme(enzyme: str) -> str:
    """Map a hitlist ``digestion_enzyme`` string to a machinery name."""
    return ENZYME_TO_MACHINERY.get(str(enzyme or "").strip(), "unknown")


def detectability_from_depth(
    n_fractions: Optional[int], n_replicates_detected: Optional[int] = None
) -> float:
    """Graded detectability from fractionation depth and reproducibility.

    Depth sets the base: shallower detection means easier detection. Replicate
    count nudges it, since a peptide found in all three replicates is a more
    reliable observation than one found in a single run.
    """
    base = _DEPTH_SCORE.get(int(n_fractions or 0), _DEFAULT_DEPTH_SCORE)
    replicates = int(n_replicates_detected or 0)
    if replicates >= 3:
        base = min(1.0, base + 0.1)
    elif replicates == 1:
        base = max(0.0, base - 0.1)
    return float(base)


def would_cleave(machinery: str, p1: str, p1_prime: str) -> bool:
    """Whether ``machinery`` cuts C-terminal to ``p1`` given the next residue.

    Only defined for the in-vitro proteases, whose rules are exact. Returns
    ``True`` for in-vivo machinery, which has no hard rule.
    """
    rule = EXCISION_P1_RULES.get(machinery)
    if rule is None:
        return True
    if p1 not in rule:
        return False
    blocked = EXCISION_P1_PRIME_BLOCKED.get(machinery, "")
    return not (p1_prime and blocked and p1_prime in blocked)


def _mismatched_machinery(
    peptide: str, c_flank: str, true_machinery: str, rng: random.Random
) -> Optional[str]:
    """Pick an enzyme whose rule this peptide's C-terminus violates."""
    if not peptide:
        return None
    p1 = peptide[-1]
    p1_prime = c_flank[0] if c_flank else ""
    candidates = [
        name
        for name in EXCISION_P1_RULES
        if name != true_machinery and not would_cleave(name, p1, p1_prime)
    ]
    if not candidates:
        return None
    return rng.choice(candidates)


def records_from_bulk_frame(
    frame,
    *,
    max_records: Optional[int] = None,
    excision_negative_ratio: float = 1.0,
    seed: int = 42,
) -> Tuple[List[BulkMSRecord], Dict[str, Any]]:
    """Build bulk records from a hitlist ``load_bulk_peptides`` frame.

    Expected columns: ``peptide``, ``digestion_enzyme``, ``cell_line_name``,
    ``uniprot_acc``, ``n_fractions_in_run``, ``n_replicates_detected``.
    """
    rng = random.Random(seed)
    rows = frame.to_dict("records") if hasattr(frame, "to_dict") else list(frame)
    if max_records is not None and 0 < max_records < len(rows):
        rows = rng.sample(rows, max_records)

    records: List[BulkMSRecord] = []
    machinery_counts: Dict[str, int] = {}
    n_excision_negatives = 0

    for row in rows:
        peptide = str(row.get("peptide") or "").strip()
        if not peptide:
            continue
        machinery = machinery_for_enzyme(row.get("digestion_enzyme"))
        if machinery == "unknown":
            continue
        machinery_counts[machinery] = machinery_counts.get(machinery, 0) + 1
        detect = detectability_from_depth(
            row.get("n_fractions_in_run"), row.get("n_replicates_detected")
        )
        records.append(
            BulkMSRecord(
                peptide=peptide,
                machinery=machinery,
                detectability_label=detect,
                # Observed under this enzyme, so this enzyme produced it.
                excision_label=1.0,
                protein_id=str(row.get("uniprot_acc") or ""),
                cell_line=str(row.get("cell_line_name") or ""),
                n_fractions=int(row.get("n_fractions_in_run") or 0),
                n_replicates_detected=int(row.get("n_replicates_detected") or 0),
                observed=True,
            )
        )

        if excision_negative_ratio > 0 and rng.random() < excision_negative_ratio:
            wrong = _mismatched_machinery(peptide, "", machinery, rng)
            if wrong is not None:
                n_excision_negatives += 1
                records.append(
                    BulkMSRecord(
                        peptide=peptide,
                        machinery=wrong,
                        # Excision only: the peptide exists, but not as a
                        # product of this enzyme. Detectability is unlabeled
                        # here because it is the same molecule either way.
                        detectability_label=None,
                        excision_label=0.0,
                        protein_id=str(row.get("uniprot_acc") or ""),
                        cell_line=str(row.get("cell_line_name") or ""),
                        observed=False,
                    )
                )

    stats = {
        "n_records": len(records),
        "n_observed": sum(1 for r in records if r.observed),
        "n_excision_negatives": n_excision_negatives,
        "machinery_counts": dict(sorted(machinery_counts.items(), key=lambda kv: -kv[1])),
    }
    return records, stats


def load_bulk_ms_records(
    *,
    cell_line: Optional[str] = None,
    digestion_enzyme: Optional[Sequence[str]] = None,
    max_records: Optional[int] = None,
    excision_negative_ratio: float = 1.0,
    protein_sequences: Optional[Mapping[str, str]] = None,
    seed: int = 42,
) -> Tuple[List[BulkMSRecord], Dict[str, Any]]:
    """Load bulk shotgun records from hitlist.

    ``protein_sequences`` is accepted for the in-silico-negative path
    (hitlist#361); it is not required for the depth-graded targets that this
    module produces today, and passing it currently has no effect beyond being
    recorded in the returned stats.
    """
    try:
        from hitlist.bulk_proteomics import load_bulk_peptides
    except ImportError as exc:  # pragma: no cover - exercised via install docs
        raise SystemExit(
            "hitlist is required for the bulk MS corpus. Install it with "
            "`pip install hitlist`."
        ) from exc

    kwargs: Dict[str, Any] = {}
    if cell_line is not None:
        kwargs["cell_line"] = cell_line
    if digestion_enzyme is not None:
        kwargs["digestion_enzyme"] = list(digestion_enzyme)
    frame = load_bulk_peptides(**kwargs)

    records, stats = records_from_bulk_frame(
        frame,
        max_records=max_records,
        excision_negative_ratio=excision_negative_ratio,
        seed=seed,
    )
    stats["in_silico_negatives_available"] = protein_sequences is not None
    return records, stats


def machinery_index(name: str) -> int:
    """Vocabulary index for a machinery name."""
    return EXCISION_MACHINERY_TO_IDX.get(name, EXCISION_MACHINERY_TO_IDX["unknown"])


def dual_corpus_transfer_set(
    mhc_peptides: Iterable[str],
    bulk_records: Sequence[BulkMSRecord],
) -> Tuple[List[BulkMSRecord], Dict[str, Any]]:
    """Peptides observed in *both* corpora, for testing detectability transfer.

    ``ms_detectability`` is trained and scored on shotgun rows but *used* on MHC
    rows, inside the elution sum. Nothing in the current evaluation asks whether
    it means anything for an MHC ligand -- presentation and detectability are
    scored on disjoint row sets, so the transfer is assumed rather than
    measured.

    Peptides present in both corpora make that measurable: their shotgun
    detection is a label, and they are MHC ligands, so a detectability term that
    generalizes should predict the former for molecules drawn from the latter.
    24,125 such peptides exist in the built indexes (9-mers 4,559, 10-mers
    3,016, 11-mers 2,628, 8-mers 1,627).

    Returns the bulk records whose peptide also occurs in ``mhc_peptides``,
    which are the rows to score, plus a length histogram for reporting.
    """
    wanted = {str(p).strip().upper() for p in mhc_peptides if str(p).strip()}
    overlap = [r for r in bulk_records if r.peptide.upper() in wanted]
    lengths: Dict[int, int] = {}
    for record in overlap:
        lengths[len(record.peptide)] = lengths.get(len(record.peptide), 0) + 1
    stats = {
        "n_mhc_peptides": len(wanted),
        "n_bulk_records": len(bulk_records),
        "n_overlap_records": len(overlap),
        "n_overlap_peptides": len({r.peptide.upper() for r in overlap}),
        "length_histogram": dict(sorted(lengths.items())),
    }
    return overlap, stats
